export const nameSymbol = Symbol('name')
export const valueSymbol = Symbol('value')
export const onChangeSymbol = Symbol('onChange')
export const disabledSymbol = Symbol('disabled')
export const updateAnswerSymbol = Symbol('updateAnswer')
export const updateShowingAnswerSymbol = Symbol('updateShowingAnswer')
